config/routes.rb
OIN::Application.routes.draw do

  get "comments/update"
  get "comments/destroy"
  resources :ideas
  resources :people, as:'profiles', controller: 'profiles'

  root 'welcome#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/models/idea.rb
class Idea
  include Mongoid::Document
  include Mongoid::Slug

  belongs_to :user
  validates :user, :presence=>true


  field :title, type: String
  validates :title, :presence=>true
  slug :title

  # This field has been given name by two mistakes. It should be called 'tags'.
  field :tagline, type: String
  validates :tagline, :presence=>true, :length=>10..160

  field :description, type: String
  validates :description, :presence=>true, :length=>10..3000

  has_many :comments, as: :subject

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  load_and_authorize_resource

  # GET /ideas
  # GET /ideas.json
  def index
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea.user = current_user

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render action: 'show', status: :created, location: @idea }
      else
        format.html { render action: 'new' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title, :tagline, :description)
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.haml
= form_for @idea do |f|
  - if @idea.errors.any?
    #error_explanation
      %h2= "#{pluralize(@idea.errors.count, "error")} prohibited this idea from being saved:"
      %ul
        - @idea.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    %br/
    = f.text_field :title, autofocus: true
  .field
    = f.label :tagline, "Tags"
    %br/
    = f.text_field :tagline
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit 'Share'

app/views/ideas/edit.html.haml
%h1 Editing idea

= render 'form'

= link_to 'Show', @idea
\|
= link_to 'Back', ideas_path

app/views/ideas/index.html.haml
%h1 Ideas

.w-row
  .w-row.snippet-row
    - @ideas.each_with_index do |idea,i|
      .w-col.w-col-4.w-col-small-6
        %a.w-clearfix.w-inline-block.snippet{:href => url_for(idea)}
          %img.lightbulb{alt:"", :src => "http://openclipart.org/image/40px/svg_to_png/85045/lightbulb3.png"}/
        .snippet-text-section
          .snippet-title=idea.title
          .snippet-text=idea.tagline

app/views/ideas/new.html.haml
%h1 Share your idea

= render 'form'

= link_to 'Back', ideas_path

app/views/ideas/show.html.haml
%p#notice= notice

%h1=@idea.title
.tagline= @idea.tagline
%p.description
  =markdown @idea.description

= link_to 'Edit', edit_idea_path(@idea)
\|
= link_to 'Back', ideas_path