config/routes.rb
OIN::Application.routes.draw do

  get "comments/update"
  get "comments/destroy"
  resources :ideas
  resources :people, as:'profiles', controller: 'profiles'

  root 'welcome#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/views/layouts/_footer.html.haml
.section.footer
  .w-container
    .w-row
      .w-col.w-col-6.left-footer-col
        .footer-text
          © 2013 Open Innovation Network. 
          -#A <a href="http://startupweekend.org/">Startup Weekend</a> graduate.
      .w-col.w-col-6.footer-nav-bar
        -#%a.footer-link{:href => "#"} Text Link
        -#%a.footer-link{:href => "#"} Text Link
        -#%a.footer-link{:href => "#"} Text Link

app/views/layouts/_header.html.haml
.section.header
  .w-container
    .w-row
      .w-col.w-col-4.company-column
        .logo
          =link_to root_path do
            %img{src:"/assets/logo_91.png", width:"91", height:"52"}
            Open Innovation Network
      .w-col.w-col-8.nav-bar
        -#%a.nav-link{:href => "#page-nav-Section 1", :target => "_self"} Nav Link
        -#%a.nav-link{:href => "#page-nav-Section-2", :target => "_self"} Nav Link

        - if current_user
          = link_to 'People', profiles_path, class: "nav-link"
        = link_to 'Ideas', ideas_path, class: "nav-link"
        - if current_user
          = link_to 'Share your idea', new_idea_path, class: "nav-link share-idea highlighted"
          = user_link current_user, "nav-link my-profile"
          = link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link"
        - else
          =link_to 'Sign Up', new_user_registration_path, class: "nav-link sign-up"
          =link_to 'Log in', new_user_session_path, class:"nav-link"
          =link_to 'Connect with Facebook', user_omniauth_authorize_path(:facebook), class: "nav-link connect-facebook"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %title Open Innovation Network
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %script{:src => "https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"}
    :javascript
      WebFont.load({
        google: {
          families: ["Montserrat:400,700"]
        }
      });

    %link{:href => "/assets/favicon.png", :rel => "icon", :type => "image/x-icon"}/
    %link{:href => "/assets/favicon.png", :rel => "apple-touch-icon"}/
  %body
    =render "layouts/header"
    #hero-bg
    =yield :before_container
    .flash
      .w-container
        - flash.each do |key, message|
          %p{class: key}=message
    .section.banner
      .w-container
        =yield :banner
    .section.main-content
      .w-container
        =yield
    =yield :after_container
    =render "layouts/footer"